packages:
  - "./apps/*/"

catalog:
  "@acdh-oeaw/eslint-config": "^1.0.10"
  "@acdh-oeaw/lib": "^0.1.12"
  "@acdh-oeaw/prettier-config": "^2.0.0"
  "@acdh-oeaw/tsconfig": "^1.1.1"
  "@types/node": "^20.14.14"
  "eslint": "^8.57.0"
  "eslint-config-turbo": "^2.0.12"
  "hono": "^4.5.4"
  "prettier": "^3.3.3"
  "typescript": "^5.5.4"
  "valibot": "^0.37.0"
